# Generated by Django 4.2.9 on 2025-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('kategori', models.CharField(choices=[('Makan', 'Makanan'), ('Minum', 'Minuman'), ('Rokok', 'Rokok'), ('Sembako', 'Sembako'), ('Lain', 'Lain-lain')], default='Lain', max_length=20, verbose_name='Kategori')),
                ('harga_modal', models.IntegerField(default=0, verbose_name='Modal (Rp)')),
                ('harga_jual', models.IntegerField(verbose_name='Harga Jual (Rp)')),
                ('stok', models.IntegerField(default=0, verbose_name='Sisa Stok')),
                ('terjual', models.IntegerField(default=0, verbose_name='Terjual')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Update')),
            ],
        ),
        migrations.DeleteModel(
            name='HideShowFilter',
        ),
        migrations.DeleteModel(
            name='ModelFilter',
        ),
        migrations.DeleteModel(
            name='PageItems',
        ),
    ]
