# Generated by Django 4.2.9 on 2025-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0002_product_delete_hideshowfilter_delete_modelfilter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HideShowFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=255)),
                ('items_per_page', models.IntegerField(default=10)),
            ],
        ),
    ]
