# Generated by Django 4.2.9 on 2025-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0003_hideshowfilter_modelfilter_pageitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kode_barang',
            field=models.CharField(default='-', max_length=50, verbose_name='Kode / Barcode'),
        ),
    ]
