# Generated by Django 4.2.9 on 2025-12-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0004_product_kode_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(max_length=50, unique=True, verbose_name='No. Struk')),
                ('total_belanja', models.IntegerField(default=0)),
                ('uang_bayar', models.IntegerField(default=0)),
                ('kembalian', models.IntegerField(default=0)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_saat_itu', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyn_dt.product')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dyn_dt.transaksi')),
            ],
        ),
    ]
