# Generated by Django 4.2.9 on 2025-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
