# Generated by Django 4.2.9 on 2025-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0007_profile_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Deskripsi singkat tentang diri Anda', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jabatan',
            field=models.CharField(blank=True, default='Staff Store', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='negara',
            field=models.CharField(blank=True, default='Indonesia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
