# Generated by Django 6.0 on 2025-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0008_profile_bio_profile_jabatan_profile_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Deskripsi singkat', null=True),
        ),
    ]
