# Generated by Django 4.2.9 on 2025-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='EL-HAYYU POS', max_length=100)),
                ('alamat', models.TextField(default='Jl. Bisnis No. 1, Internet')),
                ('no_hp', models.CharField(default='0812-3456-7890', max_length=20)),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Foto QRIS')),
            ],
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(choices=[('TUNAI', 'Tunai'), ('QRIS', 'QRIS')], default='TUNAI', max_length=10),
        ),
    ]
